name: 'APKBUILD'
description: 'Construye artefactos y los sube a upload.sh'
inputs:
  repositorio:
    description: 'Nombre del repositorio del cual se va a construir los artefactos'
    required: true
  nombre:
    description: 'Nombre del binario al cual empaquetar'
    required: true
  rama:
    description: 'Nombre de la rama del cual se va a construir los artefactos'
    required: true
    default: 'main'
  ruta-apkbuild:
    description: 'La ruta en donde se encuentra el archivo abc (datos para empaquetar akpbuild)'
    required: true
    default: 'build/APKBUILD'
outputs:
  link:
    description: 'Link de donde se alojara el binario en upload.sh'
runs:
  using: 'docker'
  image: 'docker://kedap55/poa:alpine'
  args:
    - ${{ inputs.repositorio }}
    - ${{ inputs.nombre }}
    - ${{ inputs.rama }}
    - ${{ inputs.ruta-apkbuild }}
